# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VSRQDuO5Qk3stcRZkBU9nbjf5hd0bYR
"""

# Get the Sentiment of text from a website

pip install newspaper3k

from textblob import TextBlob

pip install nltk

import nltk
from newspaper import article

pip install textblob

pip install nltk

pip install newspaper3k

from textblob import TextBlob
from newspaper import article

!pip install wikipedia
!pip install summarizer

!pip install summarizer

import wikipedia
import spacy

pageid=1999
article= wikipedia.WikipediaPage(pageid)

text= article.content
nlp= spacy.load('en_core_web_sm')
doc= nlp(text)
print(doc)

!pip install newspaper3k

from textblob import TextBlob

pip install nltk

import nltk
from newspaper import article

pip install textblob

pip install nltk

pip install newspaper3k

from textblob import TextBlob
from newspaper import article

!pip install wikipedia
!pip install summarizer

!pip install summarizer

import wikipedia
import spacy

pageid=1999
article= wikipedia.WikipediaPage(pageid)

text= article.content
nlp= spacy.load('en_core_web_sm')
doc= nlp(text)
print(doc)

blob=TextBlob(text)
sentiment=blob.sentiment.polarity
print(sentiment)

from textblob import TextBlob

text = "it was an amazing party"

blob = TextBlob(text)

print(blob.sentiment)

#newspaper article
!pip install newspaper3k

from textblob import TextBlob
import nltk
from newspaper import Article

#Get the article
url='https://www.latimes.com/world-nation/story/2020-09-20/coronavirus-aerosol-airborne-spread'
article= Article(url)

#Do some NLP
article.download()
article.parse()
nltk.download("punkt")
article.nlp()

#get the summary of the article
text=article.summary
print(text)

obj=TextBlob(text)
sentiment=obj.sentiment.polarity
print(sentiment)



if sentiment==0:
  print("the text is neutral")
elif sentiment>0:
  print("the text is positive")
else:
  print("the text is negative")

from textblob import TextBlob

text = "it was an amazing party"

blob = TextBlob(text)

print(blob.sentiment)

#newspaper article
!pip install newspaper3k

pip install newspaper3k

from textblob import TextBlob
import nltk
from newspaper import Article

#Get the article
url='https://www.latimes.com/world-nation/story/2020-09-20/coronavirus-aerosol-airborne-spread'
article= Article(url)

#Do some NLP
article.download()
article.parse()
nltk.download("punkt")
article.nlp()

#get the summary of the article
text=article.summary
print(text)

obj=TextBlob(text)
sentiment=obj.sentiment.polarity
print(sentiment)



if sentiment==0:
  print("the text is neutral")
elif sentiment>0:
  print("the text is positive")
else:
  print("the text is negative")